version: '3.7'

services:

  users:
    build:
      context: ./web1
      dockerfile: Dockerfile
    volumes:
      - ./web1:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig  # new
